version: '3.1'

services:
  local_api:
    image: node:22.14.0
    volumes:
      - ./src/nodejs:/var/nodejs
    working_dir: /var/nodejs
    environment:
      - NODE_PATH=/var/nodejs/node_modules:/var/nodejs/lambda-layers
      - API_VERSION=1.1.0
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=fake
      - AWS_SECRET_ACCESS_KEY=fake
      - EVENT_SNS=arn:aws:sns:us-east-1:000000000000:edpub_event_sns
      - METRICS_SNS=arn:aws:sns:us-east-1:000000000000:edpub_metrics_sns
      - SNS_ENDPOINT=http://goaws:4100
      - PG_USER=edpub
      - PG_HOST=postgres
      - PG_DB=edpub
      - PG_PASS=edpub
      - PG_PORT=5432
      - SIMULATED_LATENCY=1000
      - AUTH_RESPECT_EXP=true
      - AUTH_TOKEN_EXP=3600
      - AUTH_PROVIDER_URL=http://localhost:8080
      - AUTH_LOGIN_PATH=auth/login
      - AUTH_LOGOUT_PATH=auth/logout
      - AUTH_TOKEN_PATH=auth/token
      - AUTH_USER_PATH=auth/user_info
      - AUTH_CLIENT_ID=1or0vuut22m9a5r9hd4s00er9k
      - AUTH_CLIENT_SECRET=1drni35hoa4tcp63jv9dr5pa8dfj8talscgv4m7e5fabc1qemsuv
      - AUTH_CLIENT_PATH=auth
      - CLIENT_ROOT_URL=http://localhost:3000
      - DEVELOPMENT=true
    command: ["npm", "start"]
    ports:
      - 8080:8080
  goaws:
    image: pafortin/goaws
    volumes:
      - ./src/nodejs/goaws-conf:/conf
    ports:
      - 4100:4100
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: edpub
      POSTGRES_PASSWORD: edpub
    volumes:
      - ./src/postgres/:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432
  pg_admin:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: edpub@edpub.com
      PGADMIN_DEFAULT_PASSWORD: edpub
      PGADMIN_CONFIG_UPGRADE_CHECK_ENABLED: "False"
    ports:
      - 8001:80
