profile = "default"
region = "us-west-2"
stage = "test"
api_gateway_policy = "api_gateway_ngap_sandbox_policy.json"
ngap = true
ngap_lambda_policy = "ngap/system/NGAPShLambdaInVpcBasePolicy"
ngap_role_boundary = "NGAPShRoleBoundary"
vpc_enabled = true
subnet_ids = ["subnet-04be208d6a441ee8f", "subnet-0b9d5b5ff8056a58d"]
security_group_ids = ["sg-0029de45595e603f6"]
